using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Shared.Interfaces;

namespace BLL
{
	public class LanguageService : ILanguageService
	{
		private static int lastUsedInded = 0;                   // record last index to help with creating interesting responses

		private int MAX_COUNTER = 1000;

		private readonly List<string> sentencesAlreadyUsed;		//Track created sentences

		//sentence components
		private readonly List<string> subjects;
		private readonly List<string> verbs;
		private readonly List<string> nouns;

		private readonly Random randomSubject;
		private readonly Random randomVerb;
		private readonly Random randomNoun;

		public LanguageService()
		{
			this.randomSubject = new Random();
			this.randomVerb = new Random();
			this.randomNoun = new Random();

			this.sentencesAlreadyUsed = new List<string>();

			this.subjects = new List<string>() { "I", "You", "He", "She", "We", "They", "It" };
			this.verbs = InitializeVerbs();
			this.nouns = InitializeNouns();
		}

		public string GenerateSentence()
		{
			var sentence = "";
			var ctr = 0;

			while(ctr < MAX_COUNTER)
			{
				var subject = this.subjects[randomSubject.Next(0, this.subjects.Count())];
				var verb = this.verbs[randomVerb.Next(0, this.verbs.Count())];
				var noun = this.nouns[randomNoun.Next(0, this.nouns.Count())];

				sentence = string.Format("{0} {1} {2}", subject, verb, noun.ToLower());

				if (!sentencesAlreadyUsed.Any(x => x == sentence))
				{
					break;
				}

				ctr++;
			}

			sentencesAlreadyUsed.Add(sentence);

			return sentence;
		}

		private List<string> InitializeNouns()
		{
			var list = new List<string>();

			list.Add("Actor");
			list.Add("Advertisement");
			list.Add("Afternoon");
			list.Add("Airport");
			list.Add("Ambulance");
			list.Add("Animal");
			list.Add("Answer");
			list.Add("Apple");
			list.Add("Army");
			list.Add("Australia");
			list.Add("Balloon");
			list.Add("Banana");
			list.Add("Battery");
			list.Add("Beach");
			list.Add("Beard");
			list.Add("Bed");
			list.Add("Belgium");
			list.Add("Boy");
			list.Add("Branch");
			list.Add("Breakfast");
			list.Add("Brother");
			list.Add("Camera");
			list.Add("Candle");
			list.Add("Car");
			list.Add("Caravan");
			list.Add("Carpet");
			list.Add("Cartoon");
			list.Add("China");
			list.Add("Church");
			list.Add("Crayon");
			list.Add("Crowd");
			list.Add("Daughter");
			list.Add("Death");
			list.Add("Denmark");
			list.Add("Diamond");
			list.Add("Dinner");
			list.Add("Disease");
			list.Add("Doctor");
			list.Add("Dog");
			list.Add("Dream");
			list.Add("Dress");
			list.Add("Easter");
			list.Add("Egg");
			list.Add("Eggplant");
			list.Add("Egypt");
			list.Add("Elephant");
			list.Add("Energy");
			list.Add("Engine");
			list.Add("England");
			list.Add("Evening");
			list.Add("Eye");
			list.Add("Family");
			list.Add("Finland");
			list.Add("Fish");
			list.Add("Flag");
			list.Add("Flower");
			list.Add("Football");
			list.Add("Forest");
			list.Add("Fountain");
			list.Add("France");
			list.Add("Furniture");
			list.Add("Garage");
			list.Add("Gold");
			list.Add("Grass");
			list.Add("Greece");
			list.Add("Guitar");
			list.Add("Hair");
			list.Add("Hamburger");
			list.Add("Helicopter");
			list.Add("Helmet");
			list.Add("Holiday");
			list.Add("Honey");
			list.Add("Horse");
			list.Add("Hospital");
			list.Add("House");
			list.Add("Hydrogen");
			list.Add("Ice");
			list.Add("Insect");
			list.Add("Insurance");
			list.Add("Iron");
			list.Add("Island");
			list.Add("Jackal");
			list.Add("Jelly");
			list.Add("Jewellery");
			list.Add("Jordan");
			list.Add("Juice");
			list.Add("Kangaroo");
			list.Add("King");
			list.Add("Kitchen");
			list.Add("Kite");
			list.Add("Knife");
			list.Add("Lamp");
			list.Add("Lawyer");
			list.Add("Leather");
			list.Add("Library");
			list.Add("Lighter");
			list.Add("Lion");
			list.Add("Lizard");
			list.Add("Lock");
			list.Add("London");
			list.Add("Lunch");
			list.Add("Machine");
			list.Add("Magazine");
			list.Add("Magician");
			list.Add("Manchester");
			list.Add("Market");
			list.Add("Match");
			list.Add("Microphone");
			list.Add("Monkey");
			list.Add("Morning");
			list.Add("Motorcycle");
			list.Add("Nail");
			list.Add("Napkin");
			list.Add("Needle");
			list.Add("Nest");
			list.Add("Nigeria");
			list.Add("Night");
			list.Add("Notebook");
			list.Add("Ocean");
			list.Add("Oil");
			list.Add("Orange");
			list.Add("Oxygen");
			list.Add("Oyster");
			list.Add("Ghost");
			list.Add("Painting");
			list.Add("Parrot");
			list.Add("Pencil");
			list.Add("Piano");
			list.Add("Pillow");
			list.Add("Pizza");
			list.Add("Planet");
			list.Add("Plastic");
			list.Add("Portugal");
			list.Add("Potato");
			list.Add("Queen");
			list.Add("Quill");
			list.Add("Rain");
			list.Add("Rainbow");
			list.Add("Raincoat");
			list.Add("Refrigerator");
			list.Add("Restaurant");
			list.Add("River");
			list.Add("Rocket");
			list.Add("Room");
			list.Add("Rose");
			list.Add("Russia");
			list.Add("Sandwich");
			list.Add("School");
			list.Add("Scooter");
			list.Add("Shampoo");
			list.Add("Shoe");
			list.Add("Soccer");
			list.Add("Spoon");
			list.Add("Stone");
			list.Add("Sugar");
			list.Add("Sweden");
			list.Add("Teacher");
			list.Add("Telephone");
			list.Add("Television");
			list.Add("Tent");
			list.Add("Thailand");
			list.Add("Tomato");
			list.Add("Toothbrush");
			list.Add("Traffic");
			list.Add("Train");
			list.Add("Truck");
			list.Add("Uganda");
			list.Add("Umbrella");
			list.Add("Van");
			list.Add("Vase");
			list.Add("Vegetable");
			list.Add("Vulture");
			list.Add("Wall");
			list.Add("Whale");
			list.Add("Window");
			list.Add("Wire");
			list.Add("Xylophone");
			list.Add("Yacht");
			list.Add("Yak");
			list.Add("Zebra");
			list.Add("Zoo");
			list.Add("Garden");
			list.Add("Gas");
			list.Add("Girl");
			list.Add("Glass");

			return list;
		}

		private List<string> InitializeVerbs()
		{
			var list = new List<string>();

			//present
			list.Add("have");
			list.Add("do");
			list.Add("say");
			list.Add("go");
			list.Add("get");
			list.Add("make");
			list.Add("know");
			list.Add("think");
			list.Add("take");
			list.Add("see");
			list.Add("come");
			list.Add("want");
			list.Add("look");
			list.Add("use");
			list.Add("find");
			list.Add("give");
			list.Add("tell");
			list.Add("work");
			list.Add("call");
			list.Add("try");
			list.Add("ask");
			list.Add("need");
			list.Add("feel");
			list.Add("become");
			list.Add("leave");
			list.Add("put");
			list.Add("mean");
			list.Add("keep");
			list.Add("let");
			list.Add("begin");
			list.Add("seem");
			list.Add("help");
			list.Add("talk");
			list.Add("turn");
			list.Add("start");
			list.Add("show");
			list.Add("hear");
			list.Add("play");
			list.Add("run");
			list.Add("move");
			list.Add("like");
			list.Add("live");
			list.Add("believe");
			list.Add("hold");
			list.Add("bring");
			list.Add("happen");
			list.Add("write");
			list.Add("provide");
			list.Add("sit");
			list.Add("stand");
			list.Add("lose");
			list.Add("pay");
			list.Add("meet");
			list.Add("include");
			list.Add("continue");
			list.Add("set");
			list.Add("learn");
			list.Add("change");
			list.Add("lead");
			list.Add("understand");
			list.Add("watch");
			list.Add("follow");
			list.Add("sp");
			list.Add("create");
			list.Add("speak");
			list.Add("read");
			list.Add("allow");
			list.Add("add");
			list.Add("spend");
			list.Add("grow");
			list.Add("open");
			list.Add("walk");
			list.Add("win");
			list.Add("offer");
			list.Add("remember");
			list.Add("love");
			list.Add("consider");
			list.Add("appear");
			list.Add("buy");
			list.Add("wait");
			list.Add("serve");
			list.Add("die");
			list.Add("send");
			list.Add("expect");
			list.Add("build");
			list.Add("stay");
			list.Add("fall");
			list.Add("cut");
			list.Add("reach");
			list.Add("kill");
			list.Add("remain");
			list.Add("suggest");
			list.Add("raise");
			list.Add("pass");
			list.Add("sell");
			list.Add("require");
			list.Add("report");
			list.Add("decide");
			list.Add("pull");

			//past
			list.Add("had");
			list.Add("did");
			list.Add("said");
			list.Add("went");
			list.Add("got");
			list.Add("made");
			list.Add("knew");
			list.Add("thought");
			list.Add("ok");
			list.Add("saw");
			list.Add("came");
			list.Add("wanted");
			list.Add("looked");
			list.Add("used");
			list.Add("found");
			list.Add("gave");
			list.Add("ld");
			list.Add("worked");
			list.Add("called");
			list.Add("tried");
			list.Add("asked");
			list.Add("needed");
			list.Add("felt");
			list.Add("became");
			list.Add("left");
			list.Add("put");
			list.Add("meant");
			list.Add("kept");
			list.Add("let");
			list.Add("began");
			list.Add("seemed");
			list.Add("helped");
			list.Add("talked");
			list.Add("turned");
			list.Add("started");
			list.Add("showed");
			list.Add("heard");
			list.Add("played");
			list.Add("ran");
			list.Add("moved");
			list.Add("liked");
			list.Add("lived");
			list.Add("believed");
			list.Add("held");
			list.Add("brought");
			list.Add("happened");
			list.Add("wrote");
			list.Add("provided");
			list.Add("sat");
			list.Add("sod");
			list.Add("lost");
			list.Add("paid");
			list.Add("met");
			list.Add("included");
			list.Add("continued");
			list.Add("set");
			list.Add("learned");
			list.Add("changed");
			list.Add("led");
			list.Add("understood");
			list.Add("watched");
			list.Add("followed");
			list.Add("spped");
			list.Add("created");
			list.Add("spoke");
			list.Add("read");
			list.Add("allowed");
			list.Add("added");
			list.Add("spent");
			list.Add("grew");
			list.Add("opened");
			list.Add("walked");
			list.Add("won");
			list.Add("offered");
			list.Add("remembered");
			list.Add("loved");
			list.Add("considered");
			list.Add("appeared");
			list.Add("bought");
			list.Add("waited");
			list.Add("served");
			list.Add("died");
			list.Add("sent");
			list.Add("expected");
			list.Add("built");
			list.Add("stayed");
			list.Add("fell");
			list.Add("cut");
			list.Add("reached");
			list.Add("killed");
			list.Add("remained");
			list.Add("suggested");
			list.Add("raised");
			list.Add("passed");
			list.Add("sold");
			list.Add("required");
			list.Add("reported");
			list.Add("decided");
			list.Add("pulled");

			//past participle
			list.Add("have had");
			list.Add("have did");
			list.Add("have said");
			list.Add("have went");
			list.Add("have got");
			list.Add("have made");
			list.Add("have knew");
			list.Add("have thought");
			list.Add("have ok");
			list.Add("have saw");
			list.Add("have came");
			list.Add("have wanted");
			list.Add("have looked");
			list.Add("have used");
			list.Add("have found");
			list.Add("have gave");
			list.Add("have ld");
			list.Add("have worked");
			list.Add("have called");
			list.Add("have tried");
			list.Add("have asked");
			list.Add("have needed");
			list.Add("have felt");
			list.Add("have became");
			list.Add("have left");
			list.Add("have put");
			list.Add("have meant");
			list.Add("have kept");
			list.Add("have let");
			list.Add("have began");
			list.Add("have seemed");
			list.Add("have helped");
			list.Add("have talked");
			list.Add("have turned");
			list.Add("have started");
			list.Add("have showed");
			list.Add("have heard");
			list.Add("have played");
			list.Add("have ran");
			list.Add("have moved");
			list.Add("have liked");
			list.Add("have lived");
			list.Add("have believed");
			list.Add("have held");
			list.Add("have brought");
			list.Add("have happened");
			list.Add("have wrote");
			list.Add("have provided");
			list.Add("have sat");
			list.Add("have sod");
			list.Add("have lost");
			list.Add("have paid");
			list.Add("have met");
			list.Add("have included");
			list.Add("have continued");
			list.Add("have set");
			list.Add("have learned");
			list.Add("have changed");
			list.Add("have led");
			list.Add("have understood");
			list.Add("have watched");
			list.Add("have followed");
			list.Add("have spped");
			list.Add("have created");
			list.Add("have spoke");
			list.Add("have read");
			list.Add("have allowed");
			list.Add("have added");
			list.Add("have spent");
			list.Add("have grew");
			list.Add("have opened");
			list.Add("have walked");
			list.Add("have won");
			list.Add("have offered");
			list.Add("have remembered");
			list.Add("have loved");
			list.Add("have considered");
			list.Add("have appeared");
			list.Add("have bought");
			list.Add("have waited");
			list.Add("have served");
			list.Add("have died");
			list.Add("have sent");
			list.Add("have expected");
			list.Add("have built");
			list.Add("have stayed");
			list.Add("have fell");
			list.Add("have cut");
			list.Add("have reached");
			list.Add("have killed");
			list.Add("have remained");
			list.Add("have suggested");
			list.Add("have raised");
			list.Add("have passed");
			list.Add("have sold");
			list.Add("have required");
			list.Add("have reported");
			list.Add("have decided");
			list.Add("have pulled");

			return list;
		}
	}
}